/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as NosotrosImpactoRouteImport } from './routes/nosotros.impacto'
import { Route as NosotrosMisionVisionRouteImport } from './routes/nosotros.mision-vision'
import { Route as NosotrosProyectosRouteImport } from './routes/nosotros.proyectos'
import { Route as ProgramasIndexRouteImport } from './routes/programas.index'
import { Route as ProgramasSlugRouteImport } from './routes/programas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosImpactoRoute = NosotrosImpactoRouteImport.update({
  id: '/nosotros/impacto',
  path: '/nosotros/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosMisionVisionRoute = NosotrosMisionVisionRouteImport.update({
  id: '/nosotros/mision-vision',
  path: '/nosotros/mision-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosProyectosRoute = NosotrosProyectosRouteImport.update({
  id: '/nosotros/proyectos',
  path: '/nosotros/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasIndexRoute = ProgramasIndexRouteImport.update({
  id: '/programas/',
  path: '/programas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasSlugRoute = ProgramasSlugRouteImport.update({
  id: '/programas/$slug',
  path: '/programas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/historias': typeof HistoriasRoute
  '/oportunidades': typeof OportunidadesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/nosotros/impacto': typeof NosotrosImpactoRoute
  '/nosotros/mision-vision': typeof NosotrosMisionVisionRoute
  '/nosotros/proyectos': typeof NosotrosProyectosRoute
  '/programas/$slug': typeof ProgramasSlugRoute
  '/programas/': typeof ProgramasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/historias': typeof HistoriasRoute
  '/oportunidades': typeof OportunidadesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/nosotros/impacto': typeof NosotrosImpactoRoute
  '/nosotros/mision-vision': typeof NosotrosMisionVisionRoute
  '/nosotros/proyectos': typeof NosotrosProyectosRoute
  '/programas/$slug': typeof ProgramasSlugRoute
  '/programas': typeof ProgramasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/historias': typeof HistoriasRoute
  '/oportunidades': typeof OportunidadesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/nosotros/impacto': typeof NosotrosImpactoRoute
  '/nosotros/mision-vision': typeof NosotrosMisionVisionRoute
  '/nosotros/proyectos': typeof NosotrosProyectosRoute
  '/programas/$slug': typeof ProgramasSlugRoute
  '/programas/': typeof ProgramasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/historias'
    | '/oportunidades'
    | '/sobre-nosotros'
    | '/nosotros/impacto'
    | '/nosotros/mision-vision'
    | '/nosotros/proyectos'
    | '/programas/$slug'
    | '/programas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/historias'
    | '/oportunidades'
    | '/sobre-nosotros'
    | '/nosotros/impacto'
    | '/nosotros/mision-vision'
    | '/nosotros/proyectos'
    | '/programas/$slug'
    | '/programas'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/historias'
    | '/oportunidades'
    | '/sobre-nosotros'
    | '/nosotros/impacto'
    | '/nosotros/mision-vision'
    | '/nosotros/proyectos'
    | '/programas/$slug'
    | '/programas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  HistoriasRoute: typeof HistoriasRoute
  OportunidadesRoute: typeof OportunidadesRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  NosotrosImpactoRoute: typeof NosotrosImpactoRoute
  NosotrosMisionVisionRoute: typeof NosotrosMisionVisionRoute
  NosotrosProyectosRoute: typeof NosotrosProyectosRoute
  ProgramasSlugRoute: typeof ProgramasSlugRoute
  ProgramasIndexRoute: typeof ProgramasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros/impacto': {
      id: '/nosotros/impacto'
      path: '/nosotros/impacto'
      fullPath: '/nosotros/impacto'
      preLoaderRoute: typeof NosotrosImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros/mision-vision': {
      id: '/nosotros/mision-vision'
      path: '/nosotros/mision-vision'
      fullPath: '/nosotros/mision-vision'
      preLoaderRoute: typeof NosotrosMisionVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros/proyectos': {
      id: '/nosotros/proyectos'
      path: '/nosotros/proyectos'
      fullPath: '/nosotros/proyectos'
      preLoaderRoute: typeof NosotrosProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/': {
      id: '/programas/'
      path: '/programas'
      fullPath: '/programas/'
      preLoaderRoute: typeof ProgramasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/$slug': {
      id: '/programas/$slug'
      path: '/programas/$slug'
      fullPath: '/programas/$slug'
      preLoaderRoute: typeof ProgramasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  HistoriasRoute: HistoriasRoute,
  OportunidadesRoute: OportunidadesRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  NosotrosImpactoRoute: NosotrosImpactoRoute,
  NosotrosMisionVisionRoute: NosotrosMisionVisionRoute,
  NosotrosProyectosRoute: NosotrosProyectosRoute,
  ProgramasSlugRoute: ProgramasSlugRoute,
  ProgramasIndexRoute: ProgramasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
